### ISSUE TITLE
error! please, help me( /usr/bin/ld: /tmp/ex1-dfb212.o: in function `main': /workspaces/106884994/chapter10/ex1.8.c:17: undefined reference to `readLine' /usr/bin/ld: /workspaces/106884994/chapter10/ex1.8.c:21: undefined reference to `countWords' clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [<builtin>: ex1.8] Error 1

### ISSUE THREAD

**Issue by ElenaSirosh** [indradhanush/rc-shell#2]
1)I entered the code from the book and I can’t compile, the compiler gives this error:

/usr/bin/ld: /tmp/ex1-dfb212.o: in function `main':
/workspaces/106884994/chapter10/ex1.8.c:17: undefined reference to `readLine'
/usr/bin/ld: /workspaces/106884994/chapter10/ex1.8.c:21: undefined reference to `countWords'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [<builtin>: ex1.8] Error 1

2)and if you follow the instructions, it gives the following answer, please help me figure it out:

chapter10/ $ make ex1.8  -v
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
chapter10/ $

**Comment by indradhanush** [comment]
Hi @ElenaSirosh! 

It is not clear to me what book you are referring to. The error `undefined reference to readLine` usually shows up due to a linker error during compilation. Try adding `-lreadline` to your compilation command and see if resolves this issue.

In the meantime, since the issue does not appear to be related to this project, I'm going to go ahead an close the issue.
